export const ActionTypes = {
  // Invoice actions
  SELECT_INVOICE: "SELECT_INVOICE",
  CLEAR_SELECTED_INVOICE: "CLEAR_SELECTED_INVOICE",
  SET_FILTER: "SET_FILTER",
  
  // Provider view actions
  SUBMIT_OFFER: "SUBMIT_OFFER",
  RESET_OFFER: "RESET_OFFER",
  TOGGLE_SIGNED: "TOGGLE_SIGNED",
  TOGGLE_ADDITIONAL_OPTIONS: "TOGGLE_ADDITIONAL_OPTIONS",

  // Wizard actions
  WIZARD_NEXT: "WIZARD_NEXT",
  WIZARD_BACK: "WIZARD_BACK",
  WIZARD_SELECT_INVOICE: "WIZARD_SELECT_INVOICE",
  WIZARD_SET_DISCOUNT: "WIZARD_SET_DISCOUNT",
  WIZARD_ACCEPT_TERMS: "WIZARD_ACCEPT_TERMS",
  WIZARD_COMPLETE: "WIZARD_COMPLETE",
  WIZARD_RESET: "WIZARD_RESET",

  // Mobile assignment actions
  ACCEPT_ASSIGNMENT: "ACCEPT_ASSIGNMENT",
  RESET_ASSIGNMENT: "RESET_ASSIGNMENT",
} as const;
