export const ActionTypes = {
  SELECT_INVOICE: "SELECT_INVOICE",
  CLEAR_SELECTED_INVOICE: "CLEAR_SELECTED_INVOICE",
  SET_FILTER: "SET_FILTER",

  SUBMIT_OFFER: "SUBMIT_OFFER",
  RESET_OFFER: "RESET_OFFER",
  TOGGLE_SIGNED: "TOGGLE_SIGNED",
  TOGGLE_ADDITIONAL_OPTIONS: "TOGGLE_ADDITIONAL_OPTIONS",

  WIZARD_NEXT: "WIZARD_NEXT",
  WIZARD_BACK: "WIZARD_BACK",
  WIZARD_SELECT_INVOICE: "WIZARD_SELECT_INVOICE",
  WIZARD_SET_DISCOUNT: "WIZARD_SET_DISCOUNT",
  WIZARD_ACCEPT_TERMS: "WIZARD_ACCEPT_TERMS",
  WIZARD_COMPLETE: "WIZARD_COMPLETE",
  WIZARD_RESET: "WIZARD_RESET",

  ACCEPT_ASSIGNMENT: "ACCEPT_ASSIGNMENT",
  RESET_ASSIGNMENT: "RESET_ASSIGNMENT",

  // Payer actions
  SELECT_PAYER_NOTIFICATION: "SELECT_PAYER_NOTIFICATION",
  CLEAR_PAYER_NOTIFICATION: "CLEAR_PAYER_NOTIFICATION",
  ACKNOWLEDGE_ASSIGNMENT: "ACKNOWLEDGE_ASSIGNMENT",
  CONFIRM_PAYMENT: "CONFIRM_PAYMENT",
} as const;
