export const ActionTypes = {
  SELECT_INVOICE: "SELECT_INVOICE",
  CLEAR_SELECTED_INVOICE: "CLEAR_SELECTED_INVOICE",
  SET_FILTER: "SET_FILTER",
  SET_INVOICE_SEARCH: "SET_INVOICE_SEARCH",

  /** Proveedor: error de validación síncrono (sin firma) — mensaje funcional, no técnico */
  PROVIDER_VALIDATION_FAILED: "PROVIDER_VALIDATION_FAILED",
  PROVIDER_CLEAR_VALIDATION_ERROR: "PROVIDER_CLEAR_VALIDATION_ERROR",
  /** Tras useMutation (TanStack Query) — ciclo asíncrono DIAN simulado */
  PROVIDER_SUBMIT_PENDING: "PROVIDER_SUBMIT_PENDING",
  PROVIDER_SUBMIT_SUCCESS: "PROVIDER_SUBMIT_SUCCESS",
  PROVIDER_SUBMIT_FAIL: "PROVIDER_SUBMIT_FAIL",
  RESET_OFFER: "RESET_OFFER",
  TOGGLE_SIGNED: "TOGGLE_SIGNED",
  TOGGLE_ADDITIONAL_OPTIONS: "TOGGLE_ADDITIONAL_OPTIONS",

  WIZARD_NEXT: "WIZARD_NEXT",
  WIZARD_BACK: "WIZARD_BACK",
  WIZARD_SELECT_INVOICE: "WIZARD_SELECT_INVOICE",
  WIZARD_SET_DISCOUNT: "WIZARD_SET_DISCOUNT",
  WIZARD_ACCEPT_TERMS: "WIZARD_ACCEPT_TERMS",
  WIZARD_SUBMIT_PENDING: "WIZARD_SUBMIT_PENDING",
  WIZARD_SUBMIT_SUCCESS: "WIZARD_SUBMIT_SUCCESS",
  WIZARD_SUBMIT_FAIL: "WIZARD_SUBMIT_FAIL",
  WIZARD_RESET: "WIZARD_RESET",

  ASSIGNMENT_SUBMIT_PENDING: "ASSIGNMENT_SUBMIT_PENDING",
  ASSIGNMENT_SUBMIT_SUCCESS: "ASSIGNMENT_SUBMIT_SUCCESS",
  ASSIGNMENT_SUBMIT_FAIL: "ASSIGNMENT_SUBMIT_FAIL",
  RESET_ASSIGNMENT: "RESET_ASSIGNMENT",

  SELECT_PAYER_NOTIFICATION: "SELECT_PAYER_NOTIFICATION",
  CLEAR_PAYER_NOTIFICATION: "CLEAR_PAYER_NOTIFICATION",
  PAYER_OP_PENDING: "PAYER_OP_PENDING",
  PAYER_OP_RESET: "PAYER_OP_RESET",
  PAYER_ACK_SUCCESS: "PAYER_ACK_SUCCESS",
  PAYER_PAY_SUCCESS: "PAYER_PAY_SUCCESS",
} as const;
